# Config format schema number
format_version: 4

###################
## Model options
model_params:
  model_architecture: "cylinder_asym"

  output_shape:
    - 480
    - 360
    - 32

  fea_dim: 9
  out_fea_dim: 256
  num_class: 3
  num_input_features: 16
  use_norm: True
  init_size: 32


###################
## Dataset options
dataset_params:
  dataset_type: "cylinder_dataset"
  pc_dataset_type: "SemKITTI_sk"
  ignore_label: 0
  return_test: False
  fixed_volume_space: True
  label_mapping: "../config/label_mapping/rellis-3d-z-traversability.yaml"
  max_volume_space:
    - 50
    - 3.1415926
    - 2
  min_volume_space:
    - 0
    - -3.1415926
    - -4


###################
## Data_loader options
train_data_loader:
  data_path: "/media/jinhee/Extreme SSD/Datasets/GIT/Self-supervised-learning-for-Off-road-Autonomous-Driving/processed_datasets/Rellis-3D/[Ouster] RELLIS-3D (z _train-valid-test)/sequences"
  imageset: "train"
  return_ref: True
  batch_size: 2
  shuffle: True
  num_workers: 8

val_data_loader:
  data_path: "/media/jinhee/Extreme SSD/Datasets/GIT/Self-supervised-learning-for-Off-road-Autonomous-Driving/processed_datasets/Rellis-3D/[Ouster] RELLIS-3D (z _train-valid-test)/sequences"
  imageset: "val"
  return_ref: True
  batch_size: 1
  shuffle: False
  num_workers: 8


###################
## Train params
train_params:
  model_load_path: "../model_save_dir/adaptive_z_thresholding/(rellis-3d)_model_save_6_epochs.pt"
  model_save_path: "./model_load_dir/" 
  checkpoint_every_n_steps: 3900  #100
  max_num_epochs: 40  #3
  eval_every_n_steps: 3900  #100
  learning_rate: 0.001
  weight_decay: 0.001
  mixed_fp16: True
